# Generated by Django 2.1.1 on 2018-09-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userchat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('reciver', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
