# Generated by Django 2.1.7 on 2019-04-09 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0003_auto_20190408_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatedata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userstate', to=settings.AUTH_USER_MODEL),
        ),
    ]
