# Generated by Django 2.1.7 on 2019-04-11 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_realestatedata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='multi_users',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='companies.Profile'),
        ),
    ]
