# Generated by Django 2.1.7 on 2019-04-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20190412_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multi_users',
            name='roles',
            field=models.CharField(choices=[('USER', 'user'), ('VENDOR', 'vendor')], max_length=15),
        ),
    ]
