# Generated by Django 2.1.7 on 2019-04-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20190412_0209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mychl',
        ),
    ]
